name: orion

on:
  workflow_call:

env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  MACHINE_ID: orion
  CI_ROOT: ${{ secrets.ORION_CI_ROOT }}  # Env. secret variable

jobs:
  authenticate:
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 10

    steps:
    - name: Checkout ci-workflows
      uses: actions/checkout@v3
      with:
        repository: TerrenceMcGuinness-NOAA/ci-workflows

    - name: Validate global-workflow user
      run: |
        scripts/validate_user.py -g ${{ github.actor }} -p ci-workflows -d ${{ env.CI_ROOT }}
        
  checkout-build-link:
    needs: authenticate
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 100
    
    steps:
    - name: Checkout global-workflow repository
      uses: actions/checkout@v3
      with:
        path: ${{ github.run_id }}/HOMEgfs

    - name: Checkout components
      run: |
        cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
        ./checkout.sh -c -g  # Options e.g. -u can be added late

    - name: Build components
      run: |
        cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
        ./build_all.sh

    - name: Link artifacts
      run: |
        cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
        ./link_workflow.sh

  create-experiments:
    needs: checkout-build-link
    runs-on: [self-hosted, orion-ready]
    strategy:
      matrix:
        case: ["C48_S2S", "C96_atm3DVar"]

    steps:
      - name: Create Experiments ${{ matrix.case }}
        env:
          HOMEgfs_PR: ${{ env.TEST_DIR }}/HOMEgfs
          RUNTESTS: ${{ env.TEST_DIR }}/RUNTESTS
          pslot: ${{ matrix.case }}.${{ github.run_id }}
        run: |
          cd ${{ env.TEST_DIR }}/HOMEgfs
          source workflow/gw_setup.sh
          source ci/platforms/orion.sh
          ./ci/scripts/create_experiment.py --yaml ci/cases/${{ matrix.case }}.yaml --dir ${{ env.HOMEgfs_PR }}

  run-experiments:
    needs: create-experiments
    runs-on: [self-hosted, orion-ready]
    strategy:
      max-parallel: 2
      matrix:
        case: ["C48_S2S", "C96_atm3DVar"]
    steps:
      - name: Run Experiment ${{ matrix.case }}
        run: |
          cd ${{ env.TEST_DIR }}/HOMEgfs
          ./ci/scripts/run-check_ci.sh ${{ env.TEST_DIR }} ${{ matrix.case }}.${{ github.run_id }}

  clean-up:
    needs: run-experiments
    runs-on: [self-hosted, orion-ready]
    steps:
      - name: Clean-up
        run: |
          cd ${{ github.workspace }}
          rm -rf ${{ github.run_id }}
